apiVersion: v1
kind: Service
metadata:
  name: daf-miur
  labels:
    app: daf-miur
spec:
  ports:
  - name: client
    port: 3000
  selector:
    app: daf-miur
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: daf-miur
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: daf-miur
    spec:
      containers:
      - name: daf-miur
        image: nexus.daf.teamdigitale.it/daf-miur:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: client
          containerPort: 3000
